#!/usr/bin/env sh

case "$1" in
    configure)
        chown -R mobile:mobile /Library/Shadow
        chmod -R 0777 /Library/Shadow
        echo -n "shdw: "
        /usr/local/bin/shdw -g || true
    ;;

    triggered)
        echo -n "shdw: "
        /usr/local/bin/shdw -g || true
    ;;
esac

exit 0
