#!/usr/bin/env bash

case "$1" in
    triggered)
        if [ -d "/Library/Shadow" ]; then
            echo -n "shdw: "
            /usr/local/bin/shdw -g || true
        else
            echo -n "shdw: "
            /var/jb/usr/local/bin/shdw -g || true
        fi
    ;;
esac

exit 0
