#!/usr/bin/env bash

if [[ $DPKG_MAINTSCRIPT_ARCH == "iphoneos-arm64" ]]
then
    DPKG_ROOT="/var/jb"
fi

case "$1" in
    triggered)
        "$DPKG_ROOT/usr/local/bin/shdw" -g > /dev/null || true
    ;;
esac

exit 0
