#!/usr/bin/env sh

case "$1" in
    configure)
        chown -R mobile:mobile $DPKG_ROOT/Library/Shadow
        chmod -R 0777 $DPKG_ROOT/Library/Shadow
        echo -n "shdw: "
        $DPKG_ROOT/usr/local/bin/shdw -g || true
    ;;

    triggered)
        echo -n "shdw: "
        $DPKG_ROOT/usr/local/bin/shdw -g || true
    ;;
esac

exit 0
