#!/usr/bin/env python3
"""Render build-support/jb-identifiers.plist into a generated C header.

Mirrors gen-control.sh's role: one data file is the single source of truth and
this script projects it into the form the build consumes. The output is a set
of `static const char* const <sym>[]` NULL-terminated arrays plus a matching
`<sym>_count` macro, baked into ShadowCore at compile time exactly as the old
inline literals were — runtime lookup behaviour is unchanged.

Deterministic: no timestamps, no host paths, source order preserved. Writes
atomically and leaves an unchanged output untouched so make doesn't rebuild
consumers needlessly. Exits non-zero on invalid input rather than emitting
stale/partial data.

Usage: gen-jb-identifiers.py <input.plist> <output.h>
"""
import os
import plistlib
import sys
from typing import NoReturn

# Category name in the plist -> C symbol base. Categories are intentionally
# distinct (different match semantics); adding one here is the only code change
# needed to surface a new list.
CATEGORIES = {
    "NSUserDefaultsSuites": "shdw_jb_nsuserdefaults_suites",
    "JBPreferenceDomainIDs": "shdw_jb_preference_domain_ids",
}


def die(msg) -> NoReturn:
    sys.stderr.write("gen-jb-identifiers: %s\n" % msg)
    sys.exit(1)


def c_escape(value):
    """Escape a Python str into a C string literal body (no surrounding quotes).

    Emits fixed-width octal escapes for control/non-ASCII bytes so the output is
    compiler-locale-independent; the identifiers are UTF-8 bundle IDs.
    """
    out = []
    for byte in value.encode("utf-8"):
        if byte == 0x22:      # "
            out.append('\\"')
        elif byte == 0x5C:    # backslash
            out.append("\\\\")
        elif 0x20 <= byte <= 0x7E:
            out.append(chr(byte))
        else:
            out.append("\\%03o" % byte)
    return "".join(out)


def validate_entries(category, entries):
    if not isinstance(entries, list):
        die("category '%s' must be an array" % category)
    seen = set()
    for entry in entries:
        if not isinstance(entry, str):
            die("category '%s' has a non-string entry: %r" % (category, entry))
        if entry == "":
            die("category '%s' has an empty entry" % category)
        if "\x00" in entry:
            die("category '%s' entry contains NUL: %r" % (category, entry))
        if entry in seen:
            die("category '%s' has duplicate entry: %r" % (category, entry))
        seen.add(entry)


def render(data):
    lines = [
        "// GENERATED by scripts/gen-jb-identifiers.py from",
        "// build-support/jb-identifiers.plist. DO NOT EDIT; edit the plist.",
        "#ifndef SHADOW_JB_IDENTIFIERS_H",
        "#define SHADOW_JB_IDENTIFIERS_H",
        "",
    ]
    for category, symbol in CATEGORIES.items():
        if category not in data:
            die("input is missing required category '%s'" % category)
        entries = data[category]
        validate_entries(category, entries)
        lines.append("static const char* const %s[] = {" % symbol)
        for entry in entries:
            lines.append('    "%s",' % c_escape(entry))
        lines.append("    (void*)0,")
        lines.append("};")
        lines.append("#define %s_count %d" % (symbol, len(entries)))
        lines.append("")
    lines.append("#endif")
    lines.append("")
    return "\n".join(lines)


def load_plist(input_path):
    try:
        with open(input_path, "rb") as handle:
            data = plistlib.load(handle)
    except (OSError, plistlib.InvalidFileException, ValueError) as err:
        die("cannot read plist '%s': %s" % (input_path, err))
    if not isinstance(data, dict):
        die("plist root must be a dict")
    return data


def main(argv):
    if len(argv) != 3:
        die("usage: gen-jb-identifiers.py <input.plist> <output.h>")
    input_path, output_path = argv[1], argv[2]

    data = load_plist(input_path)

    for category in data:
        if category not in CATEGORIES:
            die("unknown category '%s' (known: %s)"
                % (category, ", ".join(CATEGORIES)))

    rendered = render(data)

    # Skip the write when nothing changed so dependent objects aren't rebuilt.
    try:
        with open(output_path, "r", encoding="utf-8") as handle:
            if handle.read() == rendered:
                return 0
    except OSError:
        pass

    out_dir = os.path.dirname(output_path)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    tmp_path = output_path + ".tmp.%d" % os.getpid()
    with open(tmp_path, "w", encoding="utf-8") as handle:
        handle.write(rendered)
    os.replace(tmp_path, output_path)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
